FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY Api/app ./Api/app
COPY models ./models
EXPOSE 8000
CMD ["uvicorn", "Api.app.main:app", "--host", "0.0.0.0", "--port", "8000"]
